# Summary of Model Results, Adjusted for GOC

(without `ANNOTATION:NEITHER` category)

In [1]:
from cleaning.caregivers.models import (
    load_data,
    run_logit,
    format_logit_results
)

from notebooks.models.ref import FORMULA_CONTROL_WITH_GOC

df = load_data()

In [2]:
df_without_neither = df[df["ANNOTATION"] != "NEITHER"]

In [3]:
responses = [
    "IDENTIFIED_CONV_LIM",
    "MORTALITY_3MO_FROM_HADM_ADMIT",
    "HOSPITAL_EXPIRE_FLAG"
]

formulas = {
    response:"{response} ~ {control_variables} + C(ANNOTATION, Treatment(reference='SPOUSE'))".format(control_variables=FORMULA_CONTROL_WITH_GOC, response=response)
    for response in responses
}

models = {
    response:run_logit(formulas[response], df_without_neither, disp=False)
    for response in responses
}

## GOC Conversation

N/A

## LIM Conversation

In [4]:
format_logit_results(models["IDENTIFIED_CONV_LIM"])

,odds ratio,"95% CI, lower","95% CI, upper",p-value
Intercept,0.0019,0.0006,0.0061,0.0000
SEX[T.F],0.9355,0.6590,1.3280,0.7092
MARITAL_STATUS[T.NOT MARRIED],1.4475,0.9360,2.2385,0.0964
MARITAL_STATUS[T.UNKNOWN/NOT SPECIFIED],1.2323,0.4487,3.3843,0.6853
ETHNICITY[T.OTHER],0.8838,0.5764,1.3550,0.5710
ETHNICITY[T.UNKNOWN/NOT SPECIFIED],0.6349,0.2734,1.4740,0.2904
ANNOTATION[T.BOTH],1.4980,0.9359,2.3976,0.0922
ANNOTATION[T.CHILD],1.6224,0.9364,2.8111,0.0844
ADMISSION_AGE,1.0412,1.0269,1.0557,0.0000
ELIX_SCORE,0.9515,0.8811,1.0276,0.2053
SOFA,1.1415,1.0934,1.1916,0.0000
IDENTIFIED_CONV_GOC,6.9336,4.0115,11.9840,0.0000

## Mortality (3-month)

In [5]:
format_logit_results(models["MORTALITY_3MO_FROM_HADM_ADMIT"])

,odds ratio,"95% CI, lower","95% CI, upper",p-value
Intercept,0.0181,0.0071,0.0465,0.0000
SEX[T.F],0.7450,0.5408,1.0261,0.0715
MARITAL_STATUS[T.NOT MARRIED],0.6815,0.4544,1.0222,0.0637
MARITAL_STATUS[T.UNKNOWN/NOT SPECIFIED],1.0138,0.4075,2.5224,0.9764
ETHNICITY[T.OTHER],0.8373,0.5628,1.2457,0.3810
ETHNICITY[T.UNKNOWN/NOT SPECIFIED],1.3362,0.6443,2.7712,0.4361
ANNOTATION[T.BOTH],1.3418,0.8819,2.0416,0.1697
ANNOTATION[T.CHILD],1.5293,0.9270,2.5231,0.0963
ADMISSION_AGE,1.0264,1.0138,1.0392,0.0000
ELIX_SCORE,1.0141,0.9458,1.0872,0.6942
SOFA,1.1903,1.1406,1.2420,0.0000
IDENTIFIED_CONV_GOC,2.2771,1.5536,3.3374,0.0000

## Mortality (in-hospital)

In [6]:
format_logit_results(models["HOSPITAL_EXPIRE_FLAG"])

,odds ratio,"95% CI, lower","95% CI, upper",p-value
Intercept,0.0131,0.0046,0.0379,0.0000
SEX[T.F],0.7097,0.4991,1.0091,0.0562
MARITAL_STATUS[T.NOT MARRIED],0.6691,0.4294,1.0425,0.0757
MARITAL_STATUS[T.UNKNOWN/NOT SPECIFIED],0.8663,0.3236,2.3190,0.7751
ETHNICITY[T.OTHER],0.8703,0.5612,1.3497,0.5350
ETHNICITY[T.UNKNOWN/NOT SPECIFIED],2.0638,0.9617,4.4290,0.0629
ANNOTATION[T.BOTH],1.8152,1.1451,2.8774,0.0112
ANNOTATION[T.CHILD],1.9160,1.0972,3.3458,0.0222
ADMISSION_AGE,1.0120,0.9984,1.0257,0.0845
ELIX_SCORE,1.0002,0.9268,1.0794,0.9959
SOFA,1.2427,1.1864,1.3016,0.0000
IDENTIFIED_CONV_GOC,3.3692,2.0892,5.4335,0.0000