In [1]:
import pandas as pd
import json

from IPython.display import display, HTML

In [2]:
FILE_K = '../data/raw/2020-09-22-kd-200-annotations.csv'
FILE_S = '../data/raw/2020-09-28-sz-200-annotations.csv'
FILE_original = '../data/raw/caregivers_set13Jul2020.csv'

N_ANNOTATIONS = 201

df_o = pd.read_csv(FILE_original)
df_k = pd.read_csv(FILE_K)
df_s = pd.read_csv(FILE_S)

ids_k = df_k[:N_ANNOTATIONS]['id']
ids_s = df_s[:N_ANNOTATIONS]['id']

assert ids_k.equals(ids_s)

In [3]:
df_k

,id,text,L1,L2,L3,annotationValues,labels,settings,update
0,103165,[. . .] ...,"[{""keyword"":""daughter"",""start"":8194,""length"":8}]",[],[],"{""L1_annotation"":1,""L2_annotation"":0,""L3_annot...","{""L1_title"":""child"",""L1_keywords"":""child, chil...","{""reviewMode"":""0"",""displayMode"":""0"",""numWords""...",0
1,142313,[. . .] ...,"[{""keyword"":""daughter"",""start"":9857,""length"":8}]",[],[],"{""L1_annotation"":1,""L2_annotation"":0,""L3_annot...",NaN,NaN,0
2,160258,[. . .] ...,[],"[{""keyword"":""husband"",""start"":5591,""length"":7}]",[],"{""L1_annotation"":0,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
3,134799,[. . .] ...,[],"[{""keyword"":""girlfriend"",""start"":661,""length"":...",[],"{""L1_annotation"":0,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
4,130639,[. . .] ...,[],"[{""keyword"":""fiance"",""start"":4078,""length"":6}]",[],"{""L1_annotation"":0,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
...,...,...,...,...,...,...,...,...,...
9179,138719,[. . .] ...,"[{""keyword"":""Son"",""start"":11537,""length"":3},{""...",[],[],"{""L1_annotation"":1,""L2_annotation"":0,""L3_annot...",NaN,NaN,0
9180,194618,[. . .] ...,[],"[{""keyword"":""husband"",""start"":4952,""length"":7}]",[],"{""L1_annotation"":0,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
9181,138836,[. . .] ...,"[{""keyword"":""son"",""start"":5057,""length"":3},{""k...",[],[],"{""L1_annotation"":1,""L2_annotation"":0,""L3_annot...",NaN,NaN,0
9182,134768,This is a 63yoM w/h/o 4V CABG in [**4-21**] an...,[],"[{""keyword"":""wife"",""start"":198,""length"":4},{""k...",[],"{""L1_annotation"":0,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
9183,103446,[. . .] ...,[],"[{""keyword"":""ex"",""start"":596,""length"":2},{""key...",[],"{""L1_annotation"":0,""L2_annotation"":1,""L3_annot...",NaN,NaN,0

## Spans

Span indices appear to be off by an inconsistent amount.

In [4]:
for _, row in df_k.iloc[:50].iterrows():
    l1 = json.loads(row['L1'])
    
    if l1:
        start = l1[0]['start']
        length = l1[0]['length']
        
        originals = df_o[df_o['HADM_ID'] == row['id']]['TEXT']

        assert originals.is_unique
        
        print('(start, end) = ({}, {})'.format(start, start + length))
        print('\tspan from shortened:\t', row['id'], repr(row['text'][start:start + length]))

    
        for item in originals[:5]:
            print('\tspan from original:\t', repr(item[start:start + length]))

        print(row)
        
        break

(start, end) = (8194, 8202)
	span from shortened:	 103165 'rmed wit'
	span from original:	 'daughter'
	span from original:	 ''
	span from original:	 '  ICU Ca'
	span from original:	 ''
	span from original:	 'n HCT > '
id                                                             103165
text                [. . .]                                       ...
L1                   [{"keyword":"daughter","start":8194,"length":8}]
L2                                                                 []
L3                                                                 []
annotationValues    {"L1_annotation":1,"L2_annotation":0,"L3_annot...
labels              {"L1_title":"child","L1_keywords":"child, chil...
settings            {"reviewMode":"0","displayMode":"0","numWords"...
update                                                              0
Name: 0, dtype: object

In [5]:
df_k.iloc[0]['text']

'[. . .]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 nes: \n   Multi Lumen - [**2135-7-14**] 11:45 AM \n   18 Gauge - [**2135-7-14**] 12:00 PM \n   Prophylaxis: \n   DVT: Pneumoboots \n   Stress ulcer: PPI \n   VAP: \n   Comments: \n   Communication:  Comments: \n   Code status: DNR (do not resuscitate) \n confirmed with daughter [**Name (NI) 787**] \n   Disposition: ICU \n'

## Duplicate IDs

In [6]:
unique_ids = df_k['id'].unique()
all_ids = df_k['id']

print(list(unique_ids).index(105582))
print(list(all_ids).index(105582))
print(len(all_ids[:234].unique()))

200
234
200

In [7]:
ids_k[ids_k.duplicated(keep=False)]

3      134799
10     182233
11     115545
14     182166
15     159957
16     137462
18     134497
19     154386
24     196250
26     143872
31     196422
37     159957
49     169328
51     167587
52     150509
55     123204
58     147973
59     115545
60     147973
63     196250
65     139582
72     176136
73     134497
75     182166
76     193351
77     176136
80     124083
87     167587
97     134799
101    196422
104    139582
111    193351
115    154386
119    119136
122    173305
125    151045
126    135809
129    124083
130    199655
134    151045
145    199655
151    123204
152    151772
161    137462
174    143872
183    169328
186    182233
188    119136
189    115545
190    150509
191    135809
192    123204
197    173305
200    151772
Name: id, dtype: int64

## DataFrames are different shape

In [8]:
df_k.shape

(9184, 9)

In [9]:
df_s.shape

(9187, 9)

## Texts are not the same

In [10]:
def list_texts_by_id(df):
    return df.groupby('id')\
             .agg({'text': lambda values: sorted(list(values)),
                   'annotationValues': list})\
             .reset_index()

In [11]:
df_tk = df_k.pipe(list_texts_by_id)
df_ts = df_s.pipe(list_texts_by_id)

In [12]:
(df_tk['id'] == df_ts['id']).value_counts()

True    1163
Name: id, dtype: int64

In [13]:
(df_tk['text'] == df_ts['text']).value_counts()

True     1159
False       4
Name: text, dtype: int64

In [14]:
df_t = df_tk.merge(df_ts,
                   left_on='id',
                   right_on='id',
                   suffixes=('_k', '_s'))

df_t['has_same_texts'] = df_t['text_k'] == df_t['text_s']

In [15]:
# different texts
df_dt = df_t[~df_t['has_same_texts']]

In [16]:
for index, example in df_dt.iterrows():
    print(index, example['id'], len(example['text_k']), len(example['text_s']))

508 143414 3 6
736 163321 3 3
970 182863 3 3
1076 193351 12 12

In [17]:
df_dt['id'].to_list()

[143414, 163321, 182863, 193351]

In [18]:
ex_id = 143414

display(df_k[df_k['id'] == ex_id])
display(df_s[df_s['id'] == ex_id])

,id,text,L1,L2,L3,annotationValues,labels,settings,update
352,143414,[. . .] ...,"[{""keyword"":""son"",""start"":837,""length"":3}]","[{""keyword"":""wife"",""start"":3081,""length"":4},{""...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
417,143414,[. . .] ...,"[{""keyword"":""son"",""start"":1550,""length"":3},{""k...","[{""keyword"":""wife"",""start"":4423,""length"":4},{""...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
6256,143414,[. . .] ...,"[{""keyword"":""son"",""start"":1550,""length"":3},{""k...","[{""keyword"":""wife"",""start"":4490,""length"":4},{""...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0

,id,text,L1,L2,L3,annotationValues,labels,settings,update
352,143414,[. . .] ...,"[{""keyword"":""son"",""start"":837,""length"":3}]","[{""keyword"":""wife"",""start"":3081,""length"":4},{""...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
417,143414,[. . .] ...,"[{""keyword"":""son"",""start"":1550,""length"":3},{""k...","[{""keyword"":""wife"",""start"":4423,""length"":4},{""...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
456,143414,[. . .] ...,[],"[{""keyword"":""intimate"",""start"":3614,""length"":8}]",[],"{""L1_annotation"":0,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
2963,143414,[. . .] ...,[],"[{""keyword"":""intimate"",""start"":3577,""length"":8}]",[],"{""L1_annotation"":0,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
4680,143414,[. . .] ...,[],"[{""keyword"":""intimate"",""start"":3740,""length"":8}]",[],"{""L1_annotation"":0,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
6259,143414,[. . .] ...,"[{""keyword"":""son"",""start"":1550,""length"":3},{""k...","[{""keyword"":""wife"",""start"":4490,""length"":4},{""...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0

## Labeling Investigation

In [19]:
df_k[df_k['id'] == 119803]

,id,text,L1,L2,L3,annotationValues,labels,settings,update
108,119803,[. . .] ...,"[{""keyword"":""son"",""start"":8663,""length"":3},{""k...","[{""keyword"":""husband"",""start"":8527,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
297,119803,Ms. [**Known lastname 5183**] is a 63 year-old...,"[{""keyword"":""daughter"",""start"":199,""length"":8}]","[{""keyword"":""husband"",""start"":187,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
384,119803,[. . .] ...,"[{""keyword"":""son"",""start"":8525,""length"":3},{""k...","[{""keyword"":""husband"",""start"":8389,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
1271,119803,Chief Complaint: Post-obstructive pneumonia \...,"[{""keyword"":""daughter"",""start"":255,""length"":8}]","[{""keyword"":""husband"",""start"":243,""length"":7},...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
1552,119803,63F with h/o sarcoidosis who presents on trans...,"[{""keyword"":""daughter"",""start"":132,""length"":8}]","[{""keyword"":""husband"",""start"":120,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
1928,119803,Ms. [**Known lastname 5183**] is a 63 year-old...,"[{""keyword"":""daughter"",""start"":199,""length"":8}...","[{""keyword"":""husband"",""start"":187,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
2175,119803,Ms. [**Known lastname 5183**] is a 63 year-old...,"[{""keyword"":""daughter"",""start"":199,""length"":8}]","[{""keyword"":""husband"",""start"":187,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
2466,119803,[. . .] ...,"[{""keyword"":""son"",""start"":6349,""length"":3},{""k...","[{""keyword"":""husband"",""start"":6213,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
2531,119803,Ms. [**Known lastname 5183**] is a 63 year-old...,"[{""keyword"":""daughter"",""start"":199,""length"":8}...","[{""keyword"":""husband"",""start"":187,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
2668,119803,[. . .] ...,"[{""keyword"":""son"",""start"":5722,""length"":3},{""k...","[{""keyword"":""husband"",""start"":5586,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
3238,119803,63F with h/o sarcoidosis who presents on trans...,"[{""keyword"":""daughter"",""start"":132,""length"":8}]","[{""keyword"":""husband"",""start"":120,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
3595,119803,[. . .] ...,[],"[{""keyword"":""husband"",""start"":2206,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
3682,119803,Ms. [**Known lastname 5183**] is a 63 year-old...,"[{""keyword"":""daughter"",""start"":199,""length"":8}...","[{""keyword"":""husband"",""start"":187,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
3855,119803,Chief Complaint: Post-obstructive pneumonia \...,"[{""keyword"":""daughter"",""start"":255,""length"":8}]","[{""keyword"":""husband"",""start"":243,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
3862,119803,Chief Complaint: Post-obstructive pneumonia \...,"[{""keyword"":""daughter"",""start"":255,""length"":8}]","[{""keyword"":""husband"",""start"":243,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
4243,119803,63F with h/o sarcoidosis who presents on trans...,"[{""keyword"":""daughter"",""start"":132,""length"":8}]","[{""keyword"":""husband"",""start"":120,""length"":7},...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
4652,119803,Chief Complaint: Post-obstructive pneumonia \...,"[{""keyword"":""daughter"",""start"":255,""length"":8}]","[{""keyword"":""husband"",""start"":243,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
4660,119803,[. . .] ...,"[{""keyword"":""son"",""start"":8235,""length"":3},{""k...","[{""keyword"":""husband"",""start"":8099,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
5768,119803,Ms. [**Known lastname 5183**] is a 63 year-old...,"[{""keyword"":""daughter"",""start"":199,""length"":8}]","[{""keyword"":""husband"",""start"":187,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
6072,119803,Chief Complaint: Post-obstructive pneumonia \...,"[{""keyword"":""daughter"",""start"":255,""length"":8}]","[{""keyword"":""husband"",""start"":243,""length"":7},...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
6099,119803,Ms. [**Known lastname 5183**] is a 63 year-old...,"[{""keyword"":""daughter"",""start"":199,""length"":8}...","[{""keyword"":""husband"",""start"":187,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
6326,119803,Chief Complaint: Post-obstructive pneumonia \...,"[{""keyword"":""son"",""start"":10689,""length"":3},{""...","[{""keyword"":""husband"",""start"":243,""length"":7},...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
6391,119803,63F with h/o sarcoidosis who presents on trans...,"[{""keyword"":""daughter"",""start"":132,""length"":8}]","[{""keyword"":""husband"",""start"":120,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
6681,119803,63F with h/o sarcoidosis who presents on trans...,"[{""keyword"":""daughter"",""start"":132,""length"":8}]","[{""keyword"":""husband"",""start"":120,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
6958,119803,Ms. [**Known lastname 5183**] is a 63 year-old...,"[{""keyword"":""daughter"",""start"":199,""length"":8}...","[{""keyword"":""husband"",""start"":187,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
7042,119803,[. . .] ...,"[{""keyword"":""son"",""start"":5680,""length"":3},{""k...","[{""keyword"":""husband"",""start"":5544,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
7137,119803,Chief Complaint: Post-obstructive pneumonia \...,"[{""keyword"":""son"",""start"":10726,""length"":3},{""...","[{""keyword"":""husband"",""start"":243,""length"":7},...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
7246,119803,Chief Complaint: Post-obstructive pneumonia \...,"[{""keyword"":""son"",""start"":10689,""length"":3},{""...","[{""keyword"":""husband"",""start"":243,""length"":7},...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
7495,119803,Ms. [**Known lastname 5183**] is a 63 year-old...,"[{""keyword"":""daughter"",""start"":199,""length"":8}...","[{""keyword"":""husband"",""start"":187,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
7598,119803,63F with h/o sarcoidosis who presents on trans...,"[{""keyword"":""daughter"",""start"":132,""length"":8}]","[{""keyword"":""husband"",""start"":120,""length"":7},...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
8036,119803,Ms. [**Known lastname 5183**] is a 63 year-old...,"[{""keyword"":""daughter"",""start"":199,""length"":8}]","[{""keyword"":""husband"",""start"":187,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
8515,119803,Chief Complaint: Post-obstructive pneumonia \...,"[{""keyword"":""daughter"",""start"":255,""length"":8}]","[{""keyword"":""husband"",""start"":243,""length"":7},...",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
8764,119803,63F with h/o sarcoidosis who presents on trans...,"[{""keyword"":""daughter"",""start"":132,""length"":8}]","[{""keyword"":""husband"",""start"":120,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0
8957,119803,63F with h/o sarcoidosis who presents on trans...,"[{""keyword"":""daughter"",""start"":132,""length"":8}]","[{""keyword"":""husband"",""start"":120,""length"":7}]",[],"{""L1_annotation"":1,""L2_annotation"":1,""L3_annot...",NaN,NaN,0