In [1]:
import pandas as pd
from tableone import TableOne

from cleaning.caregivers.main import load_data
from notebooks.tables.ref import columns, nonnormal

df = load_data()

table = TableOne(
    df,
    columns = columns,
    nonnormal = nonnormal
)

# Table 1
Total study population characteristics

In [2]:
table

                                                           Missing           Overall
n                                                                               1389
SEX, n (%)                           F                           0        666 (47.9)
                                     M                                    723 (52.1)
MARITAL_STATUS, n (%)                MARRIED                     0        595 (42.8)
                                     NOT MARRIED                          747 (53.8)
                                     UNKNOWN/NOT SPECIFIED                  47 (3.4)
ETHNICITY, n (%)                     (NON-HISPANIC) WHITE        0       1035 (74.5)
                                     OTHER                                283 (20.4)
                                     UNKNOWN/NOT SPECIFIED                  71 (5.1)
ADMISSION_AGE, median [Q1,Q3]                                    0  64.9 [53.3,76.9]
LOS_HADM, median [Q1,Q3]                                         0    9.0 [4.9,17.2]
DISCHARGE_LOCATION, n (%)            DEATH                       0        343 (24.7)
                                     FACILITY                             646 (46.5)
                                     HOME                                 391 (28.1)
                                     UNKNOWN/NOT SPECIFIED                   9 (0.6)
HOSPITAL_EXPIRE_FLAG, n (%)          False                       0       1046 (75.3)
                                     True                                 343 (24.7)
MORTALITY_3MO_FROM_HADM_ADMIT, n (%) False                       0        905 (65.2)
                                     True                                 484 (34.8)
MORTALITY_1Y_FROM_HADM_ADMIT, n (%)  False                       0        748 (53.9)
                                     True                                 641 (46.1)
MORTALITY_6MO_FROM_ICU_OUT, n (%)    False                       0        823 (59.3)
                                     True                                 566 (40.7)
HAS_READMISSION, n (%)               False                       0       1030 (74.2)
                                     True                                 359 (25.8)
IDENTIFIED_CONV_GOC, n (%)           False                       0        443 (31.9)
                                     True                                 946 (68.1)
IDENTIFIED_CONV_LIM, n (%)           False                       0       1026 (73.9)
                                     True                                 363 (26.1)
SOFA, median [Q1,Q3]                                             0     6.0 [4.0,9.0]
ELIX_SCORE, median [Q1,Q3]                                       0     4.0 [3.0,6.0]