In [1]:
import pandas as pd
from tableone import TableOne

from cleaning.caregivers.main import load_data

df = load_data()

## Goals of Care 2018 Model Results

### Has Child Documentation

In [2]:
TableOne(
    df,
    columns=["IDENTIFIED_CONV_GOC", "IDENTIFIED_CONV_LIM"],
    groupby="ANNOTATION_CHILD",
    pval = True
)

                                 Grouped by ANNOTATION_CHILD
                                                     Missing      Overall       False        True P-Value
n                                                                    1389         835         554
IDENTIFIED_CONV_GOC, n (%) False                           0   443 (31.9)  319 (38.2)  124 (22.4)  <0.001
                           True                                946 (68.1)  516 (61.8)  430 (77.6)
IDENTIFIED_CONV_LIM, n (%) False                           0  1026 (73.9)  694 (83.1)  332 (59.9)  <0.001
                           True                                363 (26.1)  141 (16.9)  222 (40.1)

### Has Spouse Documentation

In [3]:
TableOne(
    df,
    columns=["IDENTIFIED_CONV_GOC", "IDENTIFIED_CONV_LIM"],
    groupby="ANNOTATION_SPOUSE",
    pval = True
)

                                 Grouped by ANNOTATION_SPOUSE
                                                      Missing      Overall       False        True P-Value
n                                                                     1389         883         506
IDENTIFIED_CONV_GOC, n (%) False                            0   443 (31.9)  322 (36.5)  121 (23.9)  <0.001
                           True                                 946 (68.1)  561 (63.5)  385 (76.1)
IDENTIFIED_CONV_LIM, n (%) False                            0  1026 (73.9)  645 (73.0)  381 (75.3)   0.393
                           True                                 363 (26.1)  238 (27.0)  125 (24.7)

### Has Both Child and Spouse Documentation

In [4]:
TableOne(
    df,
    columns=["IDENTIFIED_CONV_GOC", "IDENTIFIED_CONV_LIM"],
    groupby="ANNOTATION_BOTH",
    pval = True
)

                                 Grouped by ANNOTATION_BOTH
                                                    Missing      Overall       False        True P-Value
n                                                                   1389        1187         202
IDENTIFIED_CONV_GOC, n (%) False                          0   443 (31.9)  405 (34.1)   38 (18.8)  <0.001
                           True                               946 (68.1)  782 (65.9)  164 (81.2)
IDENTIFIED_CONV_LIM, n (%) False                          0  1026 (73.9)  897 (75.6)  129 (63.9)   0.001
                           True                               363 (26.1)  290 (24.4)   73 (36.1)

### Has at Least One of Child and Spouse Documentation

In [5]:
TableOne(
    df,
    columns=["IDENTIFIED_CONV_GOC", "IDENTIFIED_CONV_LIM"],
    groupby="ANNOTATION_ANY",
    pval = True
)

                                 Grouped by ANNOTATION_ANY
                                                   Missing      Overall       False        True P-Value
n                                                                  1389         531         858
IDENTIFIED_CONV_GOC, n (%) False                         0   443 (31.9)  236 (44.4)  207 (24.1)  <0.001
                           True                              946 (68.1)  295 (55.6)  651 (75.9)
IDENTIFIED_CONV_LIM, n (%) False                         0  1026 (73.9)  442 (83.2)  584 (68.1)  <0.001
                           True                              363 (26.1)   89 (16.8)  274 (31.9)