In [1]:
import pandas as pd
from tableone import TableOne

from cleaning.caregivers.main import load_data
from notebooks.tables.ref import columns, nonnormal

df = load_data()

# Table 2
Study population stratified by child, spouse, and both (unadjusted)

## Has Child Documentation

In [2]:
TableOne(
    df,
    columns = columns,
    groupby = "ANNOTATION_CHILD",
    nonnormal = nonnormal,
    pval = True
)

                                                                  Grouped by ANNOTATION_CHILD
                                                                                      Missing            Overall              False               True P-Value
n                                                                                                           1389                835                554
SEX, n (%)                          F                                                       0         666 (47.9)         352 (42.2)         314 (56.7)  <0.001
                                    M                                                                 723 (52.1)         483 (57.8)         240 (43.3)
MARITAL_STATUS, n (%)               DIVORCED/SEPARATED                                     47          119 (8.9)           55 (6.8)          64 (12.0)  <0.001
                                    MARRIED                                                           595 (44.3)         353 (43.7)         242 (45.3)
                                    SINGLE                                                            438 (32.6)         346 (42.8)          92 (17.2)
                                    WIDOWED                                                           190 (14.2)           54 (6.7)         136 (25.5)
ETHNICITY, n (%)                    AMERICAN INDIAN/ALASKA NATIVE                           0            1 (0.1)            1 (0.1)                      0.195
                                    ASIAN                                                               40 (2.9)           16 (1.9)           24 (4.3)
                                    BLACK/AFRICAN AMERICAN                                            160 (11.5)          95 (11.4)          65 (11.7)
                                    HISPANIC/LATINO                                                     53 (3.8)           30 (3.6)           23 (4.2)
                                    OTHER                                                               29 (2.1)           17 (2.0)           12 (2.2)
                                    UNKNOWN/NOT SPECIFIED                                               71 (5.1)           46 (5.5)           25 (4.5)
                                    WHITE                                                            1035 (74.5)         630 (75.4)         405 (73.1)
LANGUAGE, n (%)                     ENGL                                                    0        1207 (86.9)         764 (91.5)         443 (80.0)  <0.001
                                    OTHER                                                               73 (5.3)           26 (3.1)           47 (8.5)
                                    PTUN                                                                40 (2.9)           19 (2.3)           21 (3.8)
                                    RUSS                                                                34 (2.4)           10 (1.2)           24 (4.3)
                                    SPAN                                                                35 (2.5)           16 (1.9)           19 (3.4)
ADMISSION_AGE, median [Q1,Q3]                                                               0   64.9 [53.3,76.9]   58.8 [47.9,69.5]   74.5 [63.2,83.1]  <0.001
LOS_HADM, median [Q1,Q3]                                                                    0     9.0 [4.9,17.2]     9.6 [5.0,18.9]     8.1 [4.7,15.4]   0.001
DISCHARGE_LOCATION, n (%)           DEAD/EXPIRED                                            0         343 (24.7)         153 (18.3)         190 (34.3)  <0.001
                                    HOME                                                              169 (12.2)         129 (15.4)           40 (7.2)
                                    HOME HEALTH CARE                                                  222 (16.0)         142 (17.0)          80 (14.4)
                                    HOSPICE                                                             30 (2.2)           21 (2.5)            9 (1.6)
                                    LONG TERM CARE HOSPITAL                                           249 (17.9)         150 (18.0)          99 (17.9)
                                    OTHER                                                               70 (5.0)           60 (7.2)           10 (1.8)
                                    SNF                                                               306 (22.0)         180 (21.6)         126 (22.7)
HOSPITAL_EXPIRE_FLAG, n (%)         False                                                   0        1046 (75.3)         682 (81.7)         364 (65.7)  <0.001
                                    True                                                              343 (24.7)         153 (18.3)         190 (34.3)
MORTALITY_3MO, n (%)                False                                                 582         323 (40.0)         181 (43.6)         142 (36.2)   0.038
                                    True                                                              484 (60.0)         234 (56.4)         250 (63.8)
MORTALITY_1Y, n (%)                 False                                                 582         166 (20.6)          90 (21.7)          76 (19.4)   0.471
                                    True                                                              641 (79.4)         325 (78.3)         316 (80.6)
IDENTIFIED_CONV_GOC, n (%)          False                                                   0         443 (31.9)         319 (38.2)         124 (22.4)  <0.001
                                    True                                                              946 (68.1)         516 (61.8)         430 (77.6)
IDENTIFIED_CONV_LIM, n (%)          False                                                   0        1026 (73.9)         694 (83.1)         332 (59.9)  <0.001
                                    True                                                              363 (26.1)         141 (16.9)         222 (40.1)
SOFA, median [Q1,Q3]                                                                        0      6.0 [4.0,9.0]      5.0 [3.0,8.0]     6.0 [4.0,10.0]  <0.001
VENT_TOTAL_HOURS, median [Q1,Q3]                                                            0  42.6 [13.7,134.5]  42.4 [13.7,154.9]  43.2 [14.0,117.2]   0.362
VENT_TOTAL_COUNT, median [Q1,Q3]                                                            0      1.0 [1.0,2.0]      1.0 [1.0,2.0]      1.0 [1.0,2.0]   0.951
VENT_FIRST_48_HADM, median [Q1,Q3]  False                                                   0         307 (22.1)         192 (23.0)         115 (20.8)   0.359
                                    True                                                             1082 (77.9)         643 (77.0)         439 (79.2)
VENT_FIRST_48_ICU, median [Q1,Q3]   False                                                   0           66 (4.8)           43 (5.1)           23 (4.2)   0.467
                                    True                                                             1323 (95.2)         792 (94.9)         531 (95.8)
VENT_TIME_FROM_HADM, median [Q1,Q3]                                                         0     4.2 [1.5,37.8]     4.7 [1.5,41.3]     3.7 [1.6,32.2]   0.375
VENT_TIME_FROM_ICU, median [Q1,Q3]                                                          0      1.9 [0.6,6.2]      1.9 [0.6,6.5]      1.9 [0.6,5.8]   0.854
[1] Chi-squared tests for the following variables may be invalid due to the low number of observations: ETHNICITY.

## Has Spouse Documentation

In [3]:
TableOne(
    df,
    columns = columns,
    groupby = "ANNOTATION_SPOUSE",
    nonnormal = nonnormal,
    pval = True
)

                                                                  Grouped by ANNOTATION_SPOUSE
                                                                                       Missing            Overall              False               True P-Value
n                                                                                                            1389                883                506
SEX, n (%)                          F                                                        0         666 (47.9)         480 (54.4)         186 (36.8)  <0.001
                                    M                                                                  723 (52.1)         403 (45.6)         320 (63.2)
MARITAL_STATUS, n (%)               DIVORCED/SEPARATED                                      47          119 (8.9)          99 (11.7)           20 (4.0)  <0.001
                                    MARRIED                                                            595 (44.3)         188 (22.2)         407 (82.1)
                                    SINGLE                                                             438 (32.6)         379 (44.8)          59 (11.9)
                                    WIDOWED                                                            190 (14.2)         180 (21.3)           10 (2.0)
ETHNICITY, n (%)                    AMERICAN INDIAN/ALASKA NATIVE                            0            1 (0.1)                               1 (0.2)  <0.001
                                    ASIAN                                                                40 (2.9)           24 (2.7)           16 (3.2)
                                    BLACK/AFRICAN AMERICAN                                             160 (11.5)         129 (14.6)           31 (6.1)
                                    HISPANIC/LATINO                                                      53 (3.8)           42 (4.8)           11 (2.2)
                                    OTHER                                                                29 (2.1)           18 (2.0)           11 (2.2)
                                    UNKNOWN/NOT SPECIFIED                                                71 (5.1)           43 (4.9)           28 (5.5)
                                    WHITE                                                             1035 (74.5)         627 (71.0)         408 (80.6)
LANGUAGE, n (%)                     ENGL                                                     0        1207 (86.9)         765 (86.6)         442 (87.4)   0.331
                                    OTHER                                                                73 (5.3)           45 (5.1)           28 (5.5)
                                    PTUN                                                                 40 (2.9)           22 (2.5)           18 (3.6)
                                    RUSS                                                                 34 (2.4)           25 (2.8)            9 (1.8)
                                    SPAN                                                                 35 (2.5)           26 (2.9)            9 (1.8)
ADMISSION_AGE, median [Q1,Q3]                                                                0   64.9 [53.3,76.9]   67.0 [53.4,79.5]   62.9 [53.2,72.7]  <0.001
LOS_HADM, median [Q1,Q3]                                                                     0     9.0 [4.9,17.2]     8.5 [4.8,16.5]    10.6 [5.4,18.9]   0.004
DISCHARGE_LOCATION, n (%)           DEAD/EXPIRED                                             0         343 (24.7)         199 (22.5)         144 (28.5)   0.060
                                    HOME                                                               169 (12.2)         101 (11.4)          68 (13.4)
                                    HOME HEALTH CARE                                                   222 (16.0)         151 (17.1)          71 (14.0)
                                    HOSPICE                                                              30 (2.2)           16 (1.8)           14 (2.8)
                                    LONG TERM CARE HOSPITAL                                            249 (17.9)         161 (18.2)          88 (17.4)
                                    OTHER                                                                70 (5.0)           46 (5.2)           24 (4.7)
                                    SNF                                                                306 (22.0)         209 (23.7)          97 (19.2)
HOSPITAL_EXPIRE_FLAG, n (%)         False                                                    0        1046 (75.3)         684 (77.5)         362 (71.5)   0.016
                                    True                                                               343 (24.7)         199 (22.5)         144 (28.5)
MORTALITY_3MO, n (%)                False                                                  582         323 (40.0)         217 (42.5)         106 (35.8)   0.074
                                    True                                                               484 (60.0)         294 (57.5)         190 (64.2)
MORTALITY_1Y, n (%)                 False                                                  582         166 (20.6)         114 (22.3)          52 (17.6)   0.130
                                    True                                                               641 (79.4)         397 (77.7)         244 (82.4)
IDENTIFIED_CONV_GOC, n (%)          False                                                    0         443 (31.9)         322 (36.5)         121 (23.9)  <0.001
                                    True                                                               946 (68.1)         561 (63.5)         385 (76.1)
IDENTIFIED_CONV_LIM, n (%)          False                                                    0        1026 (73.9)         645 (73.0)         381 (75.3)   0.393
                                    True                                                               363 (26.1)         238 (27.0)         125 (24.7)
SOFA, median [Q1,Q3]                                                                         0      6.0 [4.0,9.0]      6.0 [4.0,8.0]      6.0 [4.0,9.0]   0.016
VENT_TOTAL_HOURS, median [Q1,Q3]                                                             0  42.6 [13.7,134.5]  36.3 [12.3,116.0]  59.1 [19.0,169.4]  <0.001
VENT_TOTAL_COUNT, median [Q1,Q3]                                                             0      1.0 [1.0,2.0]      1.0 [1.0,1.0]      1.0 [1.0,2.0]   0.061
VENT_FIRST_48_HADM, median [Q1,Q3]  False                                                    0         307 (22.1)         179 (20.3)         128 (25.3)   0.035
                                    True                                                              1082 (77.9)         704 (79.7)         378 (74.7)
VENT_FIRST_48_ICU, median [Q1,Q3]   False                                                    0           66 (4.8)           44 (5.0)           22 (4.3)   0.686
                                    True                                                              1323 (95.2)         839 (95.0)         484 (95.7)
VENT_TIME_FROM_HADM, median [Q1,Q3]                                                          0     4.2 [1.5,37.8]     4.3 [1.6,30.6]     3.8 [1.4,49.9]   0.934
VENT_TIME_FROM_ICU, median [Q1,Q3]                                                           0      1.9 [0.6,6.2]      2.0 [0.8,6.5]      1.8 [0.5,5.4]   0.093
[1] Chi-squared tests for the following variables may be invalid due to the low number of observations: ETHNICITY.

## Has Both Child and Spouse Documentation

In [4]:
TableOne(
    df,
    columns = columns,
    groupby = "ANNOTATION_BOTH",
    nonnormal = nonnormal,
    pval = True
)

                                                                  Grouped by ANNOTATION_BOTH
                                                                                     Missing            Overall              False               True P-Value
n                                                                                                          1389               1187                202
SEX, n (%)                          F                                                      0         666 (47.9)         587 (49.5)          79 (39.1)   0.008
                                    M                                                                723 (52.1)         600 (50.5)         123 (60.9)
MARITAL_STATUS, n (%)               DIVORCED/SEPARATED                                    47          119 (8.9)          111 (9.7)            8 (4.1)  <0.001
                                    MARRIED                                                          595 (44.3)         425 (37.1)         170 (86.3)
                                    SINGLE                                                           438 (32.6)         427 (37.3)           11 (5.6)
                                    WIDOWED                                                          190 (14.2)         182 (15.9)            8 (4.1)
ETHNICITY, n (%)                    AMERICAN INDIAN/ALASKA NATIVE                          0            1 (0.1)            1 (0.1)                      0.023
                                    ASIAN                                                              40 (2.9)           30 (2.5)           10 (5.0)
                                    BLACK/AFRICAN AMERICAN                                           160 (11.5)         150 (12.6)           10 (5.0)
                                    HISPANIC/LATINO                                                    53 (3.8)           47 (4.0)            6 (3.0)
                                    OTHER                                                              29 (2.1)           26 (2.2)            3 (1.5)
                                    UNKNOWN/NOT SPECIFIED                                              71 (5.1)           61 (5.1)           10 (5.0)
                                    WHITE                                                           1035 (74.5)         872 (73.5)         163 (80.7)
LANGUAGE, n (%)                     ENGL                                                   0        1207 (86.9)        1045 (88.0)         162 (80.2)   0.033
                                    OTHER                                                              73 (5.3)           55 (4.6)           18 (8.9)
                                    PTUN                                                               40 (2.9)           31 (2.6)            9 (4.5)
                                    RUSS                                                               34 (2.4)           27 (2.3)            7 (3.5)
                                    SPAN                                                               35 (2.5)           29 (2.4)            6 (3.0)
ADMISSION_AGE, median [Q1,Q3]                                                              0   64.9 [53.3,76.9]   63.5 [52.5,76.9]   69.7 [61.0,77.4]  <0.001
LOS_HADM, median [Q1,Q3]                                                                   0     9.0 [4.9,17.2]     9.0 [4.9,17.2]     8.6 [4.7,16.1]   0.397
DISCHARGE_LOCATION, n (%)           DEAD/EXPIRED                                           0         343 (24.7)         262 (22.1)          81 (40.1)  <0.001
                                    HOME                                                             169 (12.2)         158 (13.3)           11 (5.4)
                                    HOME HEALTH CARE                                                 222 (16.0)         197 (16.6)          25 (12.4)
                                    HOSPICE                                                            30 (2.2)           25 (2.1)            5 (2.5)
                                    LONG TERM CARE HOSPITAL                                          249 (17.9)         209 (17.6)          40 (19.8)
                                    OTHER                                                              70 (5.0)           65 (5.5)            5 (2.5)
                                    SNF                                                              306 (22.0)         271 (22.8)          35 (17.3)
HOSPITAL_EXPIRE_FLAG, n (%)         False                                                  0        1046 (75.3)         925 (77.9)         121 (59.9)  <0.001
                                    True                                                             343 (24.7)         262 (22.1)          81 (40.1)
MORTALITY_3MO, n (%)                False                                                582         323 (40.0)         276 (41.7)          47 (32.4)   0.049
                                    True                                                             484 (60.0)         386 (58.3)          98 (67.6)
MORTALITY_1Y, n (%)                 False                                                582         166 (20.6)         139 (21.0)          27 (18.6)   0.598
                                    True                                                             641 (79.4)         523 (79.0)         118 (81.4)
IDENTIFIED_CONV_GOC, n (%)          False                                                  0         443 (31.9)         405 (34.1)          38 (18.8)  <0.001
                                    True                                                             946 (68.1)         782 (65.9)         164 (81.2)
IDENTIFIED_CONV_LIM, n (%)          False                                                  0        1026 (73.9)         897 (75.6)         129 (63.9)   0.001
                                    True                                                             363 (26.1)         290 (24.4)          73 (36.1)
SOFA, median [Q1,Q3]                                                                       0      6.0 [4.0,9.0]      6.0 [3.0,8.0]     7.0 [5.0,10.0]  <0.001
VENT_TOTAL_HOURS, median [Q1,Q3]                                                           0  42.6 [13.7,134.5]  41.3 [13.3,129.7]  51.4 [18.0,142.8]   0.048
VENT_TOTAL_COUNT, median [Q1,Q3]                                                           0      1.0 [1.0,2.0]      1.0 [1.0,2.0]      1.0 [1.0,2.0]   0.691
VENT_FIRST_48_HADM, median [Q1,Q3]  False                                                  0         307 (22.1)         259 (21.8)          48 (23.8)   0.601
                                    True                                                            1082 (77.9)         928 (78.2)         154 (76.2)
VENT_FIRST_48_ICU, median [Q1,Q3]   False                                                  0           66 (4.8)           57 (4.8)            9 (4.5)   0.972
                                    True                                                            1323 (95.2)        1130 (95.2)         193 (95.5)
VENT_TIME_FROM_HADM, median [Q1,Q3]                                                        0     4.2 [1.5,37.8]     4.3 [1.5,37.6]     3.2 [1.4,39.3]   0.529
VENT_TIME_FROM_ICU, median [Q1,Q3]                                                         0      1.9 [0.6,6.2]      1.9 [0.6,6.4]      1.8 [0.5,5.3]   0.328
[1] Chi-squared tests for the following variables may be invalid due to the low number of observations: LANGUAGE, ETHNICITY, DISCHARGE_LOCATION.

## Has at Least One of Child and Spouse Documentation

In [5]:
TableOne(
    df,
    columns = columns,
    groupby = "ANNOTATION_ANY",
    nonnormal = nonnormal,
    pval = True
)

                                                                  Grouped by ANNOTATION_ANY
                                                                                    Missing            Overall              False               True P-Value
n                                                                                                         1389                531                858
SEX, n (%)                          F                                                     0         666 (47.9)         245 (46.1)         421 (49.1)   0.314
                                    M                                                               723 (52.1)         286 (53.9)         437 (50.9)
MARITAL_STATUS, n (%)               DIVORCED/SEPARATED                                   47          119 (8.9)           43 (8.4)           76 (9.1)  <0.001
                                    MARRIED                                                         595 (44.3)         116 (22.8)         479 (57.5)
                                    SINGLE                                                          438 (32.6)         298 (58.5)         140 (16.8)
                                    WIDOWED                                                         190 (14.2)          52 (10.2)         138 (16.6)
ETHNICITY, n (%)                    AMERICAN INDIAN/ALASKA NATIVE                         0            1 (0.1)                               1 (0.1)   0.092
                                    ASIAN                                                             40 (2.9)           10 (1.9)           30 (3.5)
                                    BLACK/AFRICAN AMERICAN                                          160 (11.5)          74 (13.9)          86 (10.0)
                                    HISPANIC/LATINO                                                   53 (3.8)           25 (4.7)           28 (3.3)
                                    OTHER                                                             29 (2.1)            9 (1.7)           20 (2.3)
                                    UNKNOWN/NOT SPECIFIED                                             71 (5.1)           28 (5.3)           43 (5.0)
                                    WHITE                                                          1035 (74.5)         385 (72.5)         650 (75.8)
LANGUAGE, n (%)                     ENGL                                                  0        1207 (86.9)         484 (91.1)         723 (84.3)   0.003
                                    OTHER                                                             73 (5.3)           16 (3.0)           57 (6.6)
                                    PTUN                                                              40 (2.9)           10 (1.9)           30 (3.5)
                                    RUSS                                                              34 (2.4)            8 (1.5)           26 (3.0)
                                    SPAN                                                              35 (2.5)           13 (2.4)           22 (2.6)
ADMISSION_AGE, median [Q1,Q3]                                                             0   64.9 [53.3,76.9]   59.1 [47.5,72.4]   68.4 [56.5,79.4]  <0.001
LOS_HADM, median [Q1,Q3]                                                                  0     9.0 [4.9,17.2]     8.8 [4.8,17.9]     9.0 [4.9,16.8]   0.967
DISCHARGE_LOCATION, n (%)           DEAD/EXPIRED                                          0         343 (24.7)          90 (16.9)         253 (29.5)  <0.001
                                    HOME                                                            169 (12.2)          72 (13.6)          97 (11.3)
                                    HOME HEALTH CARE                                                222 (16.0)          96 (18.1)         126 (14.7)
                                    HOSPICE                                                           30 (2.2)           12 (2.3)           18 (2.1)
                                    LONG TERM CARE HOSPITAL                                         249 (17.9)         102 (19.2)         147 (17.1)
                                    OTHER                                                             70 (5.0)           41 (7.7)           29 (3.4)
                                    SNF                                                             306 (22.0)         118 (22.2)         188 (21.9)
HOSPITAL_EXPIRE_FLAG, n (%)         False                                                 0        1046 (75.3)         441 (83.1)         605 (70.5)  <0.001
                                    True                                                            343 (24.7)          90 (16.9)         253 (29.5)
MORTALITY_3MO, n (%)                False                                               582         323 (40.0)         122 (46.2)         201 (37.0)   0.015
                                    True                                                            484 (60.0)         142 (53.8)         342 (63.0)
MORTALITY_1Y, n (%)                 False                                               582         166 (20.6)          65 (24.6)         101 (18.6)   0.058
                                    True                                                            641 (79.4)         199 (75.4)         442 (81.4)
IDENTIFIED_CONV_GOC, n (%)          False                                                 0         443 (31.9)         236 (44.4)         207 (24.1)  <0.001
                                    True                                                            946 (68.1)         295 (55.6)         651 (75.9)
IDENTIFIED_CONV_LIM, n (%)          False                                                 0        1026 (73.9)         442 (83.2)         584 (68.1)  <0.001
                                    True                                                            363 (26.1)          89 (16.8)         274 (31.9)
SOFA, median [Q1,Q3]                                                                      0      6.0 [4.0,9.0]      5.0 [3.0,8.0]      6.0 [4.0,9.0]  <0.001
VENT_TOTAL_HOURS, median [Q1,Q3]                                                          0  42.6 [13.7,134.5]  36.0 [12.0,134.2]  46.1 [16.0,134.9]   0.014
VENT_TOTAL_COUNT, median [Q1,Q3]                                                          0      1.0 [1.0,2.0]      1.0 [1.0,1.0]      1.0 [1.0,2.0]   0.132
VENT_FIRST_48_HADM, median [Q1,Q3]  False                                                 0         307 (22.1)         112 (21.1)         195 (22.7)   0.518
                                    True                                                           1082 (77.9)         419 (78.9)         663 (77.3)
VENT_FIRST_48_ICU, median [Q1,Q3]   False                                                 0           66 (4.8)           30 (5.6)           36 (4.2)   0.268
                                    True                                                           1323 (95.2)         501 (94.4)         822 (95.8)
VENT_TIME_FROM_HADM, median [Q1,Q3]                                                       0     4.2 [1.5,37.8]     4.7 [1.5,35.2]     3.9 [1.5,39.6]   0.723
VENT_TIME_FROM_ICU, median [Q1,Q3]                                                        0      1.9 [0.6,6.2]      2.0 [0.8,6.7]      1.9 [0.5,5.6]   0.255
[1] Chi-squared tests for the following variables may be invalid due to the low number of observations: ETHNICITY.